### ISSUE TITLE
CurveNoResponse ev in contrast giving errors

### ISSUE THREAD

**Issue by nhpatscnin** [VisionandCognition/NHP-BIDS#12]
The event 'CurveNoResponse' indicates moments when the subject fixated long enough to have the hand indicators go from neutral to indicative but no response was recorded ('MISS' trial). These events are in the contrast 'curvetracing-extra'.

Sometimes these events do not occur causing the workflow to crash on an attempt to analyze the contrast ('empty contrast'). 

Suggested fix:
- build in a catch to only use contrasts that are defined > (because the events exist)
- NB!! could influence numbering of contrasts !!

**Comment by pcklink** [comment]
This is not so straightforward if we want to keep doing our analysis in the nipype pipeline and be able to do a fixed level 2 analysis over sessions. 

For now, I have created a `curvetracinginccentral` contrast where these problematic events are replaced with the central task so that the contrast becomes `curve vs central` instead of `curve vs miss`. Note that this will give similar errors when used for sessions without center-tasks....

The contrast with misses is not so great so we can probably just drop it completely.
